// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// tl_main package generated by `tlgen.py` tool

package tl_main_pkg;

  localparam logic [31:0] ADDR_SPACE_ROM   = 32'h 00000000;
  localparam logic [31:0] ADDR_SPACE_SRAM  = 32'h 10000000;
  localparam logic [31:0] ADDR_SPACE_FLASH = 32'h 20000000;
  localparam logic [31:0] ADDR_SPACE_UART0 = 32'h 40000000;
  localparam logic [31:0] ADDR_SPACE_GPIO0 = 32'h 40010000;

  localparam logic [31:0] ADDR_MASK_ROM   = 32'h 0000ffff;
  localparam logic [31:0] ADDR_MASK_SRAM  = 32'h 0000ffff;
  localparam logic [31:0] ADDR_MASK_FLASH = 32'h 0000ffff;
  localparam logic [31:0] ADDR_MASK_UART0 = 32'h 0000ffff;
  localparam logic [31:0] ADDR_MASK_GPIO0 = 32'h 0000ffff;

  localparam int N_HOST   = 2;
  localparam int N_DEVICE = 5;

  typedef enum int {
    TlRom = 0,
    TlSram = 1,
    TlFlash = 2,
    TlUart0 = 3,
    TlGpio0 = 4
  } tl_device_e;

  typedef enum int {
    TlIbexif = 0,
    TlIbexlsu = 1
  } tl_host_e;

endpackage
